github:
  clientId: a2e2d3b76a74c7df85a3
  clientSecret: 202918e78bd5441bf0e247872be9c81a62f0e02d
  redirectUri: http://localhost:8080/callback
spring:
  datasource:
    username: root
    password: qwerty123456
    url: jdbc:mysql://localhost:3306/community
    driver-class-name: com.mysql.cj.jdbc.Driver
